version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: db-hackaton
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hackaton
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678